### ISSUE TITLE
关于47ks的getinfo.m3u8，真心请教

### ISSUE THREAD

**Issue by qwervbnm** [nilaoda/m3u8_dl-js_GUI#8]
某解析站点链接http://ifkjx.com/?url=http://www.iqiyi.com/v_19rr7j313g.html

接口一中获取47ks的getinfo.m3u8的链接，以浏览器下载该文件。
然后可以用播放器直接打开该本地文件，也可以用m3u8_dl_GUI下载该本地文件以获取视频。
但就是不能直接将链接复制到m3u8_dl_GUI中以下载。

请问是需要另外设置headers吗？该如何设置？还是其他原因。困扰已久，请求解答。
另感谢开发，非常受用，谢谢。

**Comment by nilaoda** [comment]
需要设置headers（referer），你抓包看一下就知道了。
